
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  prepared_statements: false



development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: lolipop_test


production:
  <<: *default
  database: lolipop_production

  
